# Generated by Django 5.2.8 on 2025-11-15 07:40

import django.db.models.deletion
import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.CharField(default=workspaces.models.generate_workspace_id, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(help_text='Friendly name for the workspace', max_length=100)),
                ('deployment_type', models.CharField(choices=[('cloud', 'Cloud (DigitalOcean)'), ('bare_metal', 'Bare Metal'), ('aws', 'AWS'), ('gcp', 'Google Cloud'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('suspended', 'Suspended'), ('migrating', 'Migrating'), ('decommissioned', 'Decommissioned'), ('failed', 'Failed')], default='provisioning', max_length=20)),
                ('instance_url', models.URLField(blank=True, help_text='Main HTTPS endpoint')),
                ('tailscale_url', models.URLField(blank=True, help_text='Tailscale private endpoint')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('droplet_id', models.CharField(blank=True, help_text='DigitalOcean Droplet ID', max_length=100)),
                ('region', models.CharField(blank=True, help_text='Datacenter region', max_length=50)),
                ('vcpu', models.IntegerField(default=2, help_text='Virtual CPUs')),
                ('ram_gb', models.IntegerField(default=4, help_text='RAM in GB')),
                ('storage_gb', models.IntegerField(default=50, help_text='Storage in GB')),
                ('subscription_tier', models.CharField(default='starter', max_length=20)),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('decommissioned_at', models.DateTimeField(blank=True, null=True)),
                ('config_data', models.JSONField(blank=True, default=dict, help_text='Additional configuration (ports, features, etc.)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspaces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProvisioningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'provisioning_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(default=workspaces.models.generate_otp, editable=False, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('max_uses', models.IntegerField(default=1, help_text='0 = unlimited')),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspace_otps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['workspace_id'], name='workspaces_workspa_685343_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner', 'status'], name='workspaces_owner_i_448a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioninglog',
            index=models.Index(fields=['workspace', '-timestamp'], name='provisionin_workspa_31110a_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceotp',
            index=models.Index(fields=['otp_code'], name='workspace_o_otp_cod_93a638_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceotp',
            index=models.Index(fields=['workspace', 'is_active'], name='workspace_o_workspa_4a58fa_idx'),
        ),
    ]
